"""Initial setup

Revision ID: a7ebfbfd4016
Revises:
Create Date: 2023-07-10 12:31:42.726449

"""
import metagrim_common
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "a7ebfbfd4016"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo_token",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column(
            "modified_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
        sa.Column("modified_by", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("token_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("token_expires", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="gc_token_pkey"),
    )
    op.create_table(
        "demo_user",
        sa.Column("id", metagrim_common.model.types.uuid.UUID(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("modified_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("modified_by", sa.String(length=36), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("mobile", sa.String(length=15), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("user_type", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=False, server_default="INACTIVE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("mobile"),
    )

    # Insert default super admin with password admin@123
    op.execute(
        f"INSERT INTO demo_user "
        f"(id, is_deleted, email, mobile, password_hash, user_type, first_name, last_name) "
        f"VALUES "
        f"('aaa125e6-fec5-43ce-88eb-891739c3ca7e', false,'admin@demo.com', '9999911111', "
        f"'$2b$12$iXS8TFkM4Yn8AJK/.WtyfeBmVEVEbGyglaFbR01E3DCe3I/xeT5DC', 'CASHIER', 'Demo', 'User')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("demo_user")
    op.drop_table("demo_token")
    # ### end Alembic commands ###
